# Test
This script imports the `.py` file with `data_preparation` class from `data_prep_class.py`and will run tests on the class to create training and simulation datasets for each agent.

## Importing the Class

In [1]:
# importing the class
from data_prep_class import data_preparation

print("Class imported successfully!")

Class imported successfully!

## Activating the Class
Test case with `AAPL` (Apple) company and `simuluation year` being 2020.

In [2]:
# activating the class 
activate_class = data_preparation("AAPL", 2020)

print("Class activated!")

Class activated!

## Datasets

### Technical Agent's Training Data

In [3]:
# technical agent's training data
technical_agent_training = activate_class.train_data_technical_agent()

# printing the data
technical_agent_training

[*********************100%***********************]  1 of 1 completed

,moving_average_10_day,daily_price_change,daily_price_fluctuation,volatility,volatility_change,volume_change,action
Date,,,,,,,
2018-01-02,40.806047,-0.491341,0.711280,9.77,1.549999,0,1
2018-01-03,40.806047,0.070193,0.605989,9.15,0.710000,15848000,1
2018-01-04,40.806047,-0.114648,0.325222,9.22,0.390000,-28333200,1
2018-01-05,40.806047,-0.364997,0.542815,9.22,0.540000,4901600,1
2018-01-08,40.806047,0.000000,0.393076,9.52,0.570001,-12368800,1
...,...,...,...,...,...,...,...
2019-12-23,66.755757,-0.836457,0.935290,12.61,0.490000,-177406000,1
2019-12-24,67.136378,0.101246,0.474876,12.67,0.280000,-50093200,1
2019-12-26,67.597757,-1.226963,1.272764,12.65,1.030000,44642400,0
2019-12-27,68.039849,0.318193,1.410166,13.43,1.830000,53144800,0
2019-12-30,68.434456,-0.496570,1.800673,14.82,1.700001,-2151600,0

### Technical Agent's Simulation Data

In [4]:
# technical agent's simulation data
technical_agent_simulation = activate_class.simulation_data_technical_agent()

# printing the data
technical_agent_simulation

,moving_average_10_day,daily_price_change,daily_price_fluctuation,volatility,volatility_change,volume_change
Date,,,,,,
2020-01-02,73.764879,-0.990735,1.304102,12.470000,1.300000,0
2020-01-03,73.764879,-0.067495,0.983496,14.020000,3.070001,10842400
2020-01-06,73.764879,-1.448728,1.737996,13.850000,2.849999,-27935600
2020-01-07,73.764879,0.349524,0.824400,13.790000,1.070000,-9515200
2020-01-08,73.764879,-1.453554,1.754871,13.450000,2.410000,23207200
...,...,...,...,...,...,...
2020-12-23,123.469109,1.167048,1.604689,23.309999,1.550001,-80681100
2020-12-24,124.318136,-0.632146,2.295200,21.530001,1.440001,-33293600
2020-12-28,125.706927,-2.625861,3.724839,21.700001,0.970001,69556100
2020-12-29,126.979987,3.092693,4.327811,23.080000,2.730000,-3438900
2020-12-30,127.547949,1.808929,2.518895,22.770000,0.740000,-24595200

### Health Agent's Training Data

In [5]:
# health agent's train data
health_agent_training = activate_class.train_data_health_agent()

# printing the data
health_agent_training

[*********************100%***********************]  1 of 1 completed

,revenue_growth,net_income,profit_margin,debt_to_equity_ratio,current_ratio,EPS,price_to_earnings_ratio,action
Date,,,,,,,,
2018-01-02,0.679245,20065000000,0.227255,1.901547,1.242011,0.9725,10.360972,1
2018-01-03,0.679245,20065000000,0.227255,1.901547,1.242011,0.9725,10.359165,1
2018-01-04,0.679245,20065000000,0.227255,1.901547,1.242011,0.9725,10.407282,1
2018-01-05,0.679245,20065000000,0.227255,1.901547,1.242011,0.9725,10.525774,1
2018-01-08,0.679245,20065000000,0.227255,1.901547,1.242011,0.9725,10.486679,1
...,...,...,...,...,...,...,...,...
2019-12-23,0.190135,13686000000,0.213710,2.741004,1.540126,0.7600,22.519503,1
2019-12-24,0.190135,13686000000,0.213710,2.741004,1.540126,0.7600,22.540916,1
2019-12-26,0.190135,13686000000,0.213710,2.741004,1.540126,0.7600,22.988131,0
2019-12-27,0.190135,13686000000,0.213710,2.741004,1.540126,0.7600,22.979410,0
2019-12-30,0.190135,13686000000,0.213710,2.741004,1.540126,0.7600,23.115791,0

### Health Agent's Simulation Data

In [6]:
# health agent's train data
health_agent_simulation = activate_class.simulation_data_health_agent()

# printing the data
health_agent_simulation

,revenue_growth,net_income,profit_margin,debt_to_equity_ratio,current_ratio,EPS,price_to_earnings_ratio
Date,,,,,,,
2020-01-02,0.000000,22236000000,0.242172,2.804470,1.597782,1.25,14.480103
2020-01-03,0.000000,22236000000,0.242172,2.804470,1.597782,1.25,14.339331
2020-01-06,0.000000,22236000000,0.242172,2.804470,1.597782,1.25,14.453584
2020-01-07,0.000000,22236000000,0.242172,2.804470,1.597782,1.25,14.385608
2020-01-08,0.000000,22236000000,0.242172,2.804470,1.597782,1.25,14.617018
...,...,...,...,...,...,...,...
2020-12-23,0.083991,12673000000,0.195879,3.957039,1.363604,0.73,43.617865
2020-12-24,0.083991,12673000000,0.195879,3.957039,1.363604,0.73,43.954264
2020-12-28,0.083991,12673000000,0.195879,3.957039,1.363604,0.73,45.526306
2020-12-29,0.083991,12673000000,0.195879,3.957039,1.363604,0.73,44.920124
2020-12-30,0.083991,12673000000,0.195879,3.957039,1.363604,0.73,44.537108